# This file is machine-generated - editing it directly is not advised

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[attitudeFunctions]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "79dc1997ca264d57c3c7cc3389af9c9036a44c6d"
repo-rev = "master"
repo-url = "/Users/stephengagnon/.julia/dev/attitudeFunctions"
uuid = "7493c2ef-4a11-4f18-aeab-b8ca9ae8f56a"
version = "0.1.0"
