# This file is machine-generated - editing it directly is not advised

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[MATLAB]]
deps = ["Libdl", "SparseArrays"]
git-tree-sha1 = "e263657fe013cb02450c5d4210d2c50a354a5e08"
uuid = "10e44e05-a98a-55b3-a45b-ba969058deb6"
version = "0.8.3"

[[MATLABfunctions]]
deps = ["MATLAB"]
git-tree-sha1 = "f14138ac7d7caa2d43fa72763bc9dfde0b94c993"
repo-rev = "master"
repo-url = "/Users/stephengagnon/.julia/dev/MATLABfunctions"
uuid = "b30ad2df-b50a-4868-b889-ccad604802ef"
version = "0.1.0"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[attitudeFunctions]]
deps = ["LinearAlgebra", "Random"]
git-tree-sha1 = "48c777d5bb388473303252eba47861dc1617fb13"
repo-rev = "attParamTyped"
repo-url = "/Users/stephengagnon/.julia/dev/attitudeFunctions"
uuid = "7493c2ef-4a11-4f18-aeab-b8ca9ae8f56a"
version = "0.1.0"

[[lightCurveModeling]]
git-tree-sha1 = "672ed781c0fabe614e08f80c5884e3626bff98ad"
repo-rev = "master"
repo-url = "/Users/stephengagnon/.julia/dev/lightCurveModeling"
uuid = "bbb4d786-ea76-4613-b8bd-e0066326f386"
version = "0.1.0"
