name = "visibilityGroups"
uuid = "dde82544-3cd7-4f96-a535-ddb3fa36ba29"
authors = ["Stephen Gagnon <srgagnon@buffalo.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
attitudeFunctions = "7493c2ef-4a11-4f18-aeab-b8ca9ae8f56a"
lightCurveOptimization = "080a2550-1630-41fe-8750-c8cca3fe9c02"
